# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CQProject' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

    pod 'AFNetworking', '~> 3.1.0'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'ReactiveViewModel', '~> 0.3'
    pod 'Masonry', '~> 1.0.2'
    pod 'SDWebImage', '~> 5.8.4'
    pod 'REValidation', '~> 0.1.4'
    pod 'RETableViewManager', '~> 1.7'
    pod 'YYKit', :git => 'https://github.com/cfxiao/YYKit.git'
    pod 'Objection', '1.6.1'
    pod "CTMediator"
    pod "dsBridge"
#   pod 'MLeaksFinder'
#   pod 'OOMDetector', '1.3'
    pod 'fishhook', '0.2'
    
    


  target 'CQProjectTests' do
    inherit! :search_paths
    pod "Kiwi"
  end

  target 'CQProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
